logging:
  level:
    com.inspur.cloud: "DEBUG"
spring:
  liquibase:
    enabled: false
  jpa:
#    show-sql: true
    open-in-view: false
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        jdbc:
          lob:
            non_contextual_creation : true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      idle-timeout: 60000
      minimum-idle: 20
      connection-timeout: 10000
      auto-commit: true
      max-lifetime: 300000
      validation-timeout: 5000


